### PR TITLE
First Cleanup

### PR DESCRIPTION
**Pull request by CaptainShadows**
I still need to clean up a lot more but that implies MUCH less moving of files, which is good.
Note: more moving of files creates more possibilities for git to get confused.

You will NEED to copy the .project and .classpath inside of the folder to your desktop BEFORE pulling this to your computer. Paste both files back in afterwards, that way they will be ignored by git.

### CODE REVIEW

**Comment by CaptainShadows** [comment]
I think this counts as my application for " **THE PITCH PHASE**" Section I

:P

**Comment by mensreaMC** [comment]
Awesome! Good stuff man, much appreciated. I will let laser and the others
know.

**Comment by CaptainShadows** [comment]
There are others?!??!????? :P

**Comment by mensreaMC** [comment]
Yeah I have been talking about the mod for a while and some people are
kinda psyched about it.

**Comment by mensreaMC** [comment]
Cool, it worked this time.

**Comment by CaptainShadows** [comment]
yay

**Comment by mensreaMC** [comment]
Only 100k lines of code left, then hookers and cocaine for everybody!

**Pull request merged**
